employee-app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :hourlyrates
  resources :departments
  resources :projects
  resources :employees 
end

employee-app/app/models/hourly_rate.rb
class HourlyRate < ApplicationRecord
    has_many :employees
end

employee-app/app/controllers/hourlyrates_controller.rb
class HourlyratesController < ApplicationController
  def index
      @hourlyrates = HourlyRate.all
    end

    def show
      @hourlyrate = HourlyRate.find(params[:id])
    end
    
    def new
      @hourlyrate = HourlyRate.new
    end

    def edit
      @hourlyrate = HourlyRate.find(params[:id])
    end
    def create
      @hourlyrate = HourlyRate.new(hourlyrate_params)
        # respond_to is a Rails helper method that is attached to the Controller class.
        # It is referencing the response that will be sent to the View (which is going to the browser)
        respond_to do |format|
          # save --> either true or fasle
          # if true -> go to index - /departments
          # if false -> go to new - /departments/new
          if @hourlyrate.save
            # https://guides.rubyonrails.org/v2.3/routing.html#urls-and-paths
            # departments_url --> http://localhost:3000/departments
            # new_hourlyrate_url ---> http://localhost:3000/departments/new
            format.html { redirect_to hourlyrates_url, notice: 'Hourly Rate was successfully created.' }
          else
            format.html { render :new }
        end
      end
    end
    
    def update
      @hourlyrate = HourlyRate.find(params[:id])
      respond_to do |format|
        if @hourlyrate.update(hourlyrate_params)
          format.html { redirect_to hourlyrates_path, notice: 'hourlyrate was successfully updated.' }
          format.json { render :show, status: :ok, location: @hourlyrate }
        else
          format.html { render :edit }
          format.json { render json: @hourlyrate.errors, status: :unprocessable_entity }
        end
      end
    end
    
    def destroy
      @hourlyrate = HourlyRate.find(params[:id])
      @hourlyrate.destroy
      respond_to do |format|
        format.html { redirect_to hourlyrates_url, notice: 'Hourly Rate was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
    
    
    
    private
    
    def set_hourlyrate
      @hourlyrate = HourlyRate.find(params[:id])
    end
    
    def hourlyrate_params
      params.require(:hourlyrate).permit(:rate)
    end
end

employee-app/app/helpers/hourlyrates_helper.rb
module HourlyratesHelper
end

employee-app/app/views/hourlyrates/_form.html.erb
<%= form_for(hourlyrate) do |f| %>
    <% if hourlyrate.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(hourlyrate.errors.count, "error") %> prohibited this hourlyrate from being saved:</h2>
  
        <ul>
        <% hourlyrate.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= f.label :rate %>
      <%= f.text_field :rate %>
    </div>

  
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
  

employee-app/app/views/hourlyrates/edit.html.erb
<h1>Editing Hourly Rate</h1>


<%= form_for(@hourlyrate, url: hourlyrate_path(@hourlyrate), as: :hourlyrate) do |f| %>
    <div class="field">
        <%= f.label :rate %>
        <%= f.text_field :rate %>
    </div>

    <div class="actions">
        <%= f.submit %>
    </div>
    <%# f là một loại của form_for %>
<% end %>


<%= link_to 'Show', @hourlyrates_path %> |
<%= link_to 'Back', hourlyrates_path %>

employee-app/app/views/hourlyrates/index.html.erb
<h1>Hourly Rate Page</h1>

<%= debug @hourlyrate %>

<% @hourlyrates.each do |hourlyrate| %>
    <%= hourlyrate.rate %>
    <%= link_to 'Show', hourlyrate_path(hourlyrate) %>
    <td><%= link_to 'Edit', edit_hourlyrate_path(hourlyrate) %></td>
    <%= link_to 'Destroy', hourlyrate_path(hourlyrate), method: :delete, data: { confirm: 'Are you sure'} %>
<br>
<% end %>

employee-app/app/views/hourlyrates/new.html.erb
<h1>New Hourly Rate</h1>

<%= form_for(@hourlyrate, url: hourlyrates_path, as: :hourlyrate) do |f| %>
    <div class="field">
        <%= f.label :rate %>
        <%= f.text_field :rate %>
    </div>

    <div class="actions">
        <%= f.submit %>
    </div>
    <%# f là một loại của form_for %>
<% end %>

employee-app/app/views/hourlyrates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rate:</strong>
  <%= @hourlyrate.rate %>
</p>



<%= link_to 'Edit', edit_hourlyrate_path(@hourlyrate) %> |
<%= link_to 'Back', hourlyrates_path %>