employee-app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :hourlyrates
  resources :departments
  resources :projects
  resources :employees 
end

employee-app/app/models/department.rb
class Department < ApplicationRecord
    has_many :employees

    # Validation
    # https://guides.rubyonrails.org/active_record_validations.html#validations-overview
    validates :name, presence: true, uniqueness: true
end

employee-app/app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  def index
    @departments = Department.all # return array
  end

  def new
    # Method: GET
    # Mission: Render a form.
    # In a form, you will able to fill in the department's name.
    # Init an empty object
    # instance variable `@`
    @department = Department.new
  end

  def create
    @department = Department.new(departments_params)
    
    # respond_to is a Rails helper method that is attached to the Controller class.
    # It is referencing the response that will be sent to the View (which is going to the browser)
    respond_to do |format|
      # save --> either true or fasle
      # if true -> go to index - /departments
      # if false -> go to new - /departments/new
      if @department.save
        # https://guides.rubyonrails.org/v2.3/routing.html#urls-and-paths
        # departments_url --> http://localhost:3000/departments
        # new_hourlyrate_url ---> http://localhost:3000/departments/new
        format.html { redirect_to departments_url, notice: 'Department was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def show
    # Detail page
    @department = Department.find(params[:id])
  end
  
  def update
    @department = Department.find(params[:id])
    respond_to do |format|
      if @department.update(departments_params)
        format.html { redirect_to @department, notice: 'department was successfully updated.' }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @department = Department.find(params[:id])
  end

  def destroy
    # Find
    # have to find Id
    @department = Department.find(params[:id])
    @department.destroy
    respond_to do |format|
      format.html { redirect_to departments_url, notice: 'Department was successfully created.' }
      format.json { head :no_content}
    end 
  end

  private

  def set_department
    @department = Department.find(params[:id])
  end

  def departments_params
    # Strong Parameter
    # https://api.rubyonrails.org/classes/ActionController/Parameters.html
    params.require(:department).permit(:name)
  end
end

employee-app/app/helpers/departments_helper.rb
module DepartmentsHelper
end

employee-app/app/views/departments/_form.html.erb
<%= form_for(department) do |f| %>
    <% if department.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(department.errors.count, "error") %> prohibited this department from being saved:</h2>
  
        <ul>
        <% department.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>
  

employee-app/app/views/departments/edit.html.erb
<h1>Editing Department</h1>

<%= render 'form', department: @department %>

<%= link_to 'Show', @department %> |
<%= link_to 'Back', departments_path %>

employee-app/app/views/departments/index.html.erb
<h1>Department Page</h1>

<p id="notice"><%= notice %></p>

<% @departments.each do |department|%>
    <%= department.name %>
    <%= link_to 'Show', department %>
    <td><%= link_to 'Edit', edit_department_path(department) %></td>
    <%= link_to 'Destroy', department, method: :delete, data: { confirm: 'Are you sure'} %>
    <br>
<% end %>

employee-app/app/views/departments/new.html.erb
<h1>New Department</h1>


<%= form_for(@department) do |f| %>
    <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <div class="actions">
        <%= f.submit %>
    </div>
    <%# f là một loại của form_for %>
<% end %>

employee-app/app/views/departments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @department.name %>
</p>


<%= link_to 'Edit', edit_department_path(@department) %> |
<%= link_to 'Back', departments_path %>