employee-app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :hourlyrates
  resources :departments
  resources :projects
  resources :employees 
end

employee-app/app/models/employee.rb
class Employee < ApplicationRecord
    belongs_to :project
    belongs_to :department
    belongs_to :hourly_rate
end

employee-app/app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
    def index
        @employees = Employee.all
    end

    def view
        @employee = Employee.new
    end

    def show
        @employee = Employee.find(params[:id])
    end

    def edit
        @employee = Employee.find(params[:id])
    end

    def new
      # Method: GET
      # Mission: Render a form.
      # In a form, you will able to fill in the employee's name.
      # Init an empty object
      # instance variable `@`
      @employee = Employee.new  
    end

    def destroy
      # Find
      # have to find Id
      @employee = Employee.find(params[:id])
      @employee.destroy
      respond_to do |format|
        format.html { redirect_to employees_url, notice: 'Employee was successfully created.' }
        format.json { head :no_content}
      end 
    end
    
    def update
        @employee = Employee.find(params[:id])
        
        respond_to do |format|  
          if @employee.update(employees_params)
            format.html { redirect_to @employee, notice: 'employee was successfully updated.' }
          else
            format.html { render :edit }
          end
        end
      end
    

    def create
      @employee = Employee.new(employees_params)
        respond_to do |format|
          byebug
          if @employee.save
            format.html { redirect_to employees_url, notice: 'employee was successfully created.' }
          else
            format.html { render :new }
        end
      end
    end


    private

    def set_employee
        @employee = Employee.find(params[:id])
    end

    def employees_params
        params.require(:employee).permit(:department_id, :project_id, :hourly_rate_id, :name)
    end
end

employee-app/app/helpers/employees_helper.rb
module EmployeesHelper
end

employee-app/app/views/employees/_form.html.erb
<%= form_for(employee) do |f| %>
    <% if employee.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>
  
        <ul>
        <% employee.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= f.text_field :name %></br>
      <%= f.collection_select :department_id, Department.all, :id, :name %>
    </div>
    <div class="field">
      <%= f.collection_select :project_id, Project.all, :id, :code %>
    </div>
    <div class="field">
      <%= f.collection_select :hourly_rate_id, HourlyRate.all, :id, :rate %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>
  

employee-app/app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

employee-app/app/views/employees/index.html.erb
<h1>Employee Page</h1>

<p id="notice"><%= notice %></p>

<% @employees.each do |employee|%>
    <td>
    <tr><%= employee.department.name %></tr>
    <tr><%= employee.department.id %></tr>
    <tr><%= employee.project.manager %></tr>
    <tr><%= employee.project.id %></tr>
    <tr><%= employee.project.code %></tr>



    <%= link_to 'Show', employee %>
    <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
    <%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure'} %>
    <br>
  </td>
<% end %>

employee-app/app/views/employees/new.html.erb
<h1>Employee Page</h1>


<%= form_for(@employee) do |f| %>

    <div class="field">
        <%= f.text_field :name %></br>
        <%= f.collection_select :department_id, Department.all, :id, :name %>
    </div>
    <div class="field">
        <%= f.collection_select :project_id, Project.all, :id, :code %>
    </div>
    <div class="field">
        <%= f.collection_select :hourly_rate_id, HourlyRate.all, :id, :rate %>
    </div>

    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

employee-app/app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rate:</strong>
  <%= @employee.department.name %>
  <%= @employee.department.id %>

</p>



<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>