employee/config/routes.rb
Rails.application.routes.draw do
  resources :ems
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

employee/app/models/em.rb
class Em < ApplicationRecord
end

employee/app/controllers/ems_controller.rb
class EmsController < ApplicationController
  before_action :set_em, only: [:show, :edit, :update, :destroy]

  # GET /ems
  # GET /ems.json
  def index
    @ems = Em.all
  end

  # GET /ems/1
  # GET /ems/1.json
  def show
  end

  # GET /ems/new
  def new
    @em = Em.new
  end

  # GET /ems/1/edit
  def edit
  end

  # POST /ems
  # POST /ems.json
  def create
    @em = Em.new(em_params)

    respond_to do |format|
      if @em.save
        format.html { redirect_to @em, notice: 'Em was successfully created.' }
        format.json { render :show, status: :created, location: @em }
      else
        format.html { render :new }
        format.json { render json: @em.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ems/1
  # PATCH/PUT /ems/1.json
  def update
    respond_to do |format|
      if @em.update(em_params)
        format.html { redirect_to @em, notice: 'Em was successfully updated.' }
        format.json { render :show, status: :ok, location: @em }
      else
        format.html { render :edit }
        format.json { render json: @em.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ems/1
  # DELETE /ems/1.json
  def destroy
    @em.destroy
    respond_to do |format|
      format.html { redirect_to ems_url, notice: 'Em was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_em
      @em = Em.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def em_params
      params.require(:em).permit(:name, :department, :price)
    end
end

employee/app/helpers/ems_helper.rb
module EmsHelper
end

employee/app/views/ems/_form.html.erb
<%= form_for(em) do |f| %>
  <% if em.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(em.errors.count, "error") %> prohibited this em from being saved:</h2>

      <ul>
      <% em.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_area :name %>
  </div>

  <div class="field">
    <%= f.label :department %>
    <%= f.text_area :department %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

employee/app/views/ems/edit.html.erb
<h1>Editing Em</h1>

<%= render 'form', em: @em %>

<%= link_to 'Show', @em %> |
<%= link_to 'Back', ems_path %>

employee/app/views/ems/index.html.erb
<p id="notice"><%= notice %></p>


<table>
  <thead>
    <tr>
      <div class="head">
        <h1>Employee</h1>
      </div>
    </tr>
  </thead>

  <tbody>
    <div class="employee">
      <% @ems.each do |em| %>
        <tr>
          <td><%= em.name %></td>
          <td><%= em.department %></td>
          <td><span class="price"><%= number_to_currency(em.price) %></span></td>
          <td><%= link_to 'Edit', edit_em_path(em) %></td>
          <td><%= link_to 'Delete', em, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </div>
  </tbody>
</table>
<br>


<div style="text-align: center;">
  <%= link_to 'New Employee', new_em_path %>
</div>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

employee/app/views/ems/new.html.erb
<h1>New Employee</h1>

<%= render 'form', em: @em %>

<div style="text-align: center;">
    <%= link_to 'Back', ems_path %>
</div>

employee/app/views/ems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @em.name %>
</p>

<p>
  <strong>Department:</strong>
  <%= @em.department %>
</p>

<p>
  <strong>Price:</strong>
  <%= @em.price %>
</p>

<%= link_to 'Edit', edit_em_path(@em) %> |
<%= link_to 'Back', ems_path %>

employee/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Employee</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>